### ISSUE TITLE
Cannot compile on up-to-date Ubuntu

### ISSUE THREAD

**Issue by JonathanWilbur** [Kampbell/isode-8.0#8]
Hello,

I am trying to create a Docker image for Quipu (I might do so for the whole ISODE while I am at it). I am building off of the `ubuntu` Docker image. Starting from a fresh `ubuntu` image, these are the commands that I run, in order:

```
apt update
apt install -y git build-essential flex bison
git clone https://github.com/Kampbell/isode-8.0.git
cd isode-8.0
cp config/linux.h h/config.h (Missing .h in documentation)
cp config/linux.make config/CONFIG.make
cp config/*.local support/
./make everything
./make isnt-everything
```

I get a multitude of errors. I fixed some of them manually (and I'm not a C programmer by trade, so I'm not really sure I actually "fixed" them). I won't even bother pasting all of the errors, because there are so many, and they are all so different, but some of them seem to indicate that I have wrong versions of some things. Note that the errors below are for the `vt` make target; if you are wondering why I am not hitting errors on the FTAM targets, it is because I removed those to see if it was just a problem with the FTAM targets.

Here is one:

```
/usr/lib/gcc/x86_64-linux-gnu/9/include/varargs.h:4:2: error: #error "GCC no longer implements <varargs.h>."
```

And here is another:

```
vt.c:1545:14: error: macro "va_start" requires 2 arguments, but only 1 given
 1545 |  va_start (ap);
```

And this error:

```
vt.c:548:15: error: 'TIOCGETP' undeclared (first use in this function); did you mean 'TIOCGETD'?
  548 |  if (ioctl(0, TIOCGETP, (char *)&ottyb) == -1) {
```

I did a search for `TIOCGETP` and found [this website](https://tldp.org/LDP/lpg/node143.html), which says that "if symbols such as TIOCGETP are undefined, you will need to link against libbsd." This seems to tell me that I am not linking something that should be linked. I tried adding `-lbsd` to `OPTIONS` in `linux.make`, with no luck.

Okay, now to summarize as a question: **Are there specific versions of GCC, Make, LD, the GNU library, etc. that I need for this to build, run and install?** A lot of these errors seem to point to me having wrong versions of something. Thank you!

**Comment by JonathanWilbur** [comment]
I tried on `ubuntu:xenial` (several years old now), and I get far fewer errors, but I still get this:

```
/isode-8.0/ftam2/ftam-dir.c:243: undefined reference to `_getcwd'
```

And this:

```
/isode-8.0/compat/chkpassword.c:88: undefined reference to `crypt'
```

**Comment by JonathanWilbur** [comment]
Sorry, I realize now that this is a duplicate.

**Comment by zosrothko** [comment]
That's a compiler version issue. 
Either you need to use a GCC compiler that supports the <varargs.h> include to avoid this error
#error "GCC no longer implements <varargs.h>.
Either you should change the code as explained here: https://stackoverflow.com/questions/24950362/gcc-no-longer-implements-varargs-h
